websearch:
  use_rag: true
  rag_config_path: examples/rag/config.yaml
  use_summary: false
  input_file: examples/rag/output.json
  input_queries: examples/rag/queries.jsonl
  output_file: examples/websearchRAG/enhanced_results_trial.json
  n_loops: 2
  max_searches: 10
  llm_config:
    temperature: 0.2
    llm: OpenMeditron/meditron3-8b
