data_path: /scratch/mzhang7/CTE/data/sample/jsonl/merged/merged_results.jsonl

pp_modules:
  - type: chunker 
    args:
      chunking_strategy: sentence
  - type: translator
    args:
      target_language: en
      attachment_tag: <attachment>
output:
  output_path: /scratch/mzhang7/CTE/data/sample/jsonl/post_processed
  save_each_step: True
