indexer:
  dense_model:
    model_name: sentence-transformers/all-MiniLM-L6-v2
    is_multimodal: false
    # To enable vision mode
    # model_name: Qwen/Qwen2.5-VL-3B-Instruct
    # is_multimodal: true
  sparse_model:
    model_name: splade
    is_multimodal: false
  db:
    uri: ./proc_demo.db
    name: my_db
collection_name: my_docs
documents_path: 'examples/postprocessor/outputs/merged/results.jsonl'
