indexer:
  dense_model:
    model_name: abhinand/MedEmbed-large-v0.1
  sparse_model:
    model_name: splade
  db:
    uri: /mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/chunk_guidelines_medembed_ivf.db
collection_name: who
documents_path: "/mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/pp/2___🧩 Chunker.jsonl"
batch_size: 64