indexer:
  dense_model:
    model_name: dunzhang/stella_en_400M_v5
  sparse_model:
    model_name: splade
  db:
    uri: /mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/chunk_guidelines_stella_ivf.db
collection_name: who
documents_path: "/mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/pp/2___🧩 Chunker.jsonl"
batch_size: 64