indexer:
  dense_model:
    model_name: intfloat/e5-large-v2
  sparse_model:
    model_name: splade
  db:
    uri: /mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/chunk_guidelines_e5_ivf.db
collection_name: who
documents_path: "/mnt/mlo/scratch/homes/mmore/datasets/who_guidelines/processed/extraction_results_47k/pp/2___🧩 Chunker.jsonl"
batch_size: 64