# RAG Config
rag: 
  # LLM Config
  llm: 
    llm_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0" # "epfl-llm/meditron-70b" # "gpt-4o-mini" # Anything supported
    max_new_tokens: 100
    temperature: 0.8
  # Retriever Config
  retriever:
    db:
      uri: ./proc_demo.db
      name: my_db
    hybrid_search_weight: 0.5
    k: 5
  # Prompt Args
  system_prompt: "Answer the question using the context.\n\nContext: {context}"
# Mode Config
mode: api
mode_args:
  endpoint: '/rag'
  port: 8000
  host: 'localhost'
