name: 🧪 PyTest unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    name: test (py${{ matrix.python-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        run: pipx install uv

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies - process (using uv)
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[process,index,rag,api,cpu,dev,websearch]"

      - name: Show installed cohere and langchain-cohere versions
        run: |
          source .venv/bin/activate
          uv pip show cohere || echo "Cohere not installed"
          uv pip show langchain-cohere || echo "Langchain-cohere not installed"

      - name: Run tests - process
        run: |
          source .venv/bin/activate
          pytest --ignore=tests/test_colvision.py

      - name: Install dependencies - colvision
        run: |
          uv venv .venv-colvision
          source .venv-colvision/bin/activate
          uv pip install -e ".[colvision,cpu,dev]"

      - name: Run tests - colvision
        run: |
          source .venv-colvision/bin/activate
          pytest tests/test_colvision.py
